# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "datacastle/windows7"
  config.vm.provision :shell, path: "InstallChocolatey.bat"
  config.vm.provision :shell, path: "InstallJava.bat"
  config.vm.provision :shell, path: "InstallToolandFiles.bat"

  config.vm.provider "virtualbox" do |vb|

      vb.gui = true
	  
    vb.memory = "2048"
  end

end
